spring.application.name=springbackend

spring.datasource.url=jdbc:postgresql://localhost:5432/eduquestdb
spring.datasource.username=eduquestuser
spring.datasource.password=eduquestpass

# Use update to preserve data between restarts
spring.jpa.hibernate.ddl-auto=update

# Only run the initialization scripts if the database is empty
spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:sql/schema.sql
spring.sql.init.data-locations=classpath:sql/data.sql
spring.sql.init.separator=;;;

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

jwt.secret=lEdvcWK3FAioHt25cY8XTnfNvYtpjUVwdsvG03EjOXU=

spring.ai.ollama.base-url=http://localhost:11434
spring.ai.ollama.chat.options.model=gemma4:e2b