import React from "react";
import {useNavigation} from "@react-navigation/native";
import {ScrollView, StyleSheet, Text, TouchableOpacity, View} from "react-native";

const MathGamesIndex: React.FC = () => {
    const navigation = useNavigation();

    const games = [
        {
            id: 1,
            title: 'Speed Calculation',
            component: 'CalculationGame',
            description: 'Test your speed with basic arithmetic!'
        },
        {
            id: 2,
            title: 'AI Math Adventures',
            component: 'AppliedMath',
            description: 'Solving real-world problems generated by AI.'
        },
        // More science games can be added.
    ];

    return (
        <ScrollView style={styles.container}>
            <View style={styles.header}>
                <Text style={styles.title}>Science Games</Text>
                <Text style={styles.subtitle}>Choose a game to start learning</Text>
            </View>

            <View style={styles.gamesGrid}>
                {games.map(game => (
                    <TouchableOpacity
                        key={game.id}
                        style={styles.gameCard}
                        onPress={() => {
                            // 使用相對路徑導航
                            if (game.id === 1) {
                                // 導航到 math/CalculationGame
                                navigation.navigate('math/CalculationGame' as never);
                            }
                            if (game.id === 2) {
                                // 導航到 math/HumanBodyGame
                                navigation.navigate('math/AppliedMath' as never);
                            }
                        }}
                    >
                        <View style={styles.gameCardContent}>
                            <Text style={styles.gameTitle}>{game.title}</Text>
                            <Text style={styles.gameDescription}>
                                {game.description}
                            </Text>
                        </View>
                    </TouchableOpacity>
                ))}
            </View>
        </ScrollView>
    );
};

const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#f5f5f5',
    },
    header: {
        padding: 20,
        backgroundColor: '#fff',
        marginBottom: 20,
    },
    title: {
        fontSize: 32,
        fontWeight: 'bold',
        color: '#333',
        marginBottom: 10,
    },
    subtitle: {
        fontSize: 16,
        color: '#666',
    },
    gamesGrid: {
        padding: 15,
    },
    gameCard: {
        backgroundColor: '#fff',
        borderRadius: 15,
        marginBottom: 20,
        elevation: 3,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
        overflow: 'hidden',
    },
    gameCardContent: {
        padding: 25,
    },
    gameTitle: {
        fontSize: 22,
        fontWeight: '600',
        color: '#333',
        marginBottom: 10,
    },
    gameDescription: {
        fontSize: 16,
        color: '#666',
        lineHeight: 24,
    },
});

export default MathGamesIndex;